name: 4.- Uploading an artifact 2
on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # Cambia la versión si es necesario

      # Restore dependencies (if any)
      - name: Restore dependencies
        run: dotnet restore ./GitHubActionsTests/GitHubActionsTests.csproj

      # Build the project
      - name: Build the project
        run: dotnet build --no-restore ./GitHubActionsTests/GitHubActionsTests.csproj

      # Run the project (this creates the test.txt file)
      - name: Run the project
        run: dotnet run --project ./GitHubActionsTests/GitHubActionsTests.csproj

      # Upload the test.txt as an artifact
      - name: Upload test.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: 'D:/a/GitHubActionsTests/GitHubActionsTests/test.txt'

