name: Environment Variable Demo

on: push

jobs:
  demo:
    runs-on: ubuntu-latest  # Puedes usar windows-latest también si lo prefieres

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Echo the GITHUB_WORKSPACE environment variable
      - name: Show GITHUB_WORKSPACE path
        run: echo "The workspace directory is $GITHUB_WORKSPACE"

      # Another example with more variables
      - name: Show some default environment variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Run number: $GITHUB_RUN_NUMBER"
          echo "Actor (who triggered the workflow): $GITHUB_ACTOR"
