name: .NET Build with Cache

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: | 
          ~/.nuget/packages
          !~/.nuget/packages/microsoft.netcore.app.*/**
          !~/.nuget/packages/microsoft.aspnetcore.app.*/**
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
